name = "GibbsTypePriors"
uuid = "1266804b-bd95-4f6b-9d1e-355bae9cde8b"
authors = ["konkam <guillaume.konkamking.work@gmail.com>"]
version = "0.1.0"

[deps]
Memoization = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[compat]
julia = "^1"
Nemo = "0"
SpecialFunctions = "0.9, 0.10"
StatsFuns = "0"
Memoization = "0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
